config/routes.rb
Kickstarter::Application.routes.draw do

root :to => 'projects#index'
  resources :projects do
    collection do
      get :top_hits
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :abstract, :budget, :description, :title

  def self.expensive
  	Project.where('budget > ?', 100)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, :only => [:edit, :update, :destroy]

  
  def new
  	@project = Project.new
  end

  def create
  	#@project  = Project.new(params[:project])
    if @project.save
      redirect_to projects_path
    else
      redirect_to :back
    end
  end


  def index
    @projects = Project.all 
  end

  def edit
 #   @project = Project.find params[:id]
  end

  def update
   # @project = Project.find params[:id]
    @project.update_attributes(params[:project])
    redirect_to projects_path
  end

   def destroy
   # @project = Project.find params[:id]
    @project.destroy
    redirect_to projects_path
  end
   
   def top_hits
    @projects = Project.where('budget > ?',100 )
   end

   private
   def find_project
     @project = Project.find params[:id]
   end

  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kickstarter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<%= f.label :title %>
  </br>
	<%= f.text_field :title %>
	</br>
  <%= f.label :description %>
   </br>
  <%= f.text_field :description %>
  </br>
  <%= f.label :abstract%>
   </br>
  <%= f.text_field :abstract %>
  </br>
  <%= f.label :budget %>
  </br>
   <%= f.text_field :budget %>
   </br>
   <%= f.submit button_name %>
  <% end %>

app/views/projects/edit.html.erb
<h2> Edit selected project </h2>
<%=link_to "Back", projects_path%>
</br> 
</br>

<%= render 'form' ,button_name: 'Update' %>

  

app/views/projects/index.html.erb
<h1>Project Database</h1>

 <%=link_to "Add new project", new_project_path%> </br>
 <%=link_to "Top Hits", top_hits_projects_path%> 

<table border="1" width="100%">
	<tr>
		<td>
			Title
		</td>
		<td>
			Description
		</td>
		<td>
			Abstract	
		</td>
		<td>
			Budget
		</td>
		<td>
			Option	
		</td>
		<td>
			Delete
		</td>
	</tr>

	
		<% @projects.each do |project|%>
		<tr>
			<td> <%=project.title%> </td> 

		 	<td> <%=project.description%> </td> 
		 	<td> <%=project.abstract%> </td> 
		 	<td> <%=project.budget%> </td> 

		 	<td> <%=link_to "edit", edit_project_path(project.id)%> </td>
		 	<td> <%=link_to "delete", project_path(project.id), method: 'delete', confirm: 'Are you sure you want to delete?' %> </td>
		 	<td> <%=link_to "View Details", projects_path %></td> </br> </br>
		 </tr>

		 	
		<%end%>
	
</table>

app/views/projects/new.html.erb
<h1> Please, submit the form </h1>
<h2> Add new project </h2>
<%= render 'form', button_name: "Submit" %>

app/views/projects/show.html.erb
<table border="1" width="100%">
	<tr>
		<td>
			Title
		</td>
		<td>
			Description
		</td>
		<td>
			Abstract	
		</td>
		<td>
			Budget
		</td>
		<td>
			Option	
		</td>
		<td>
			Delete
		</td>
	</tr>

	
		<% @projects.each do |project|%>
		<tr>
			<td> <%=project.title%> </td> 

		 	<td> <%=project.description%> </td> 
		 	<td> <%=project.abstract%> </td> 
		 	<td> <%=project.budget%> </td> 

		 	<td> <%=link_to "edit", edit_project_path(project.id)%> </td>
		 	<td> <%=link_to "delete", project_path(project.id), method: 'delete', confirm: 'Are you sure you want to delete?' %> </td>
		 <% end %>

app/views/projects/top_hits.html.erb
<table border="1">
	<% @projects.each do |project| %>
	<tr>
		<td> <%= project.title %> </td>
		<td> <%= project.budget %> </td>
	</tr>
	<% end %>

</table>